[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { path = "../vendor/log"}

tarator = { path = "../tarator"}
egui_glfw_gl = { path = "../vendor/egui_glfw_gl" }
